CREATE DATABASE ORG;
SHOW DATABASES;
USE ORG;
CREATE TABLE Worker(
	WORKER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME CHAR(25), 
    LAST_NAME CHAR(25),
    SALARY INT(15),
    JOINING_DATA DATETIME,
    DEPARTMENT CHAR(25)
);
INSERT INTO Worker 
	(WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATA, DEPARTMENT) VALUES
    (001, 'Pratham', 'Tetgure', 100000, '14-02-20 09.00.00', 'HR');

CREATE TABLE Title(
	WORKER_REF_ID INT,
    WORKER_TITLE CHAR(25), 
    AFFECTED_FROM DATETIME,
    FOREIGN KEY (WORKER_REF_ID)
		REFERENCES Worker(WORKER_ID)
        ON DELETE CASCADE
);
INSERT INTO TITLE (WORKER_REF_ID, WORKER_TITLE, AFFECTED_FROM) VALUES
(001, 'MANAGER', '2016-02-20 00:00:00');
CREATE TABLE BONUS(
	WORKER_REF_ID INT,
    BONUS_AMOUNT INT(10), 
    BONUS_DATE DATETIME,
    FOREIGN KEY (WORKER_REF_ID)
		REFERENCES Worker(WORKER_ID)
        ON DELETE CASCADE
);
INSERT INTO BONUS (WORKER_REF_ID, BONUS_AMOUNT, BONUS_DATE) VALUES
(001, 5000, '16-02-20');

INSERT INTO Worker VALUES 
(002, 'Shruti', 'Tetgure', 120000, '14-03-21 10.00.00', 'ADMIN');
INSERT INTO Worker VALUES 
(003, 'YONO', 'Tetgure', 120000, '14-03-23 11.00.00', NULL);
