SELECT FIRST_NAME, SALARY FROM Worker;
SELECT 44+11;
SELECT now();
SELECT lcase('PRATHAM');
SELECT ucase('pratham');
SELECT * FROM Worker WHERE SALARY <= 100000;
SELECT * FROM worker WHERE DEPARTMENT ='ADMIN';
SELECT * FROM Worker WHERE SALARY BETWEEN 80000 and 90000;
-- Reduce OR Statments 
-- HR and admin 
SELECT * FROM Worker WHERE DEPARTMENT = 'HR' OR DEPARTMENT = 'ADMIN';
-- Better Way is IN Command 
SELECT * FROM Worker WHERE DEPARTMENT IN ('HR', 'ADMIN'); 
-- NOT Used 
SELECT * FROM Worker WHERE DEPARTMENT NOT IN ('HR', 'ADMIN'); 
-- Is NULL Filteration
SELECT * FROM Worker WHERE DEPARTMENT IS NULL;
-- Pattern Searching OR Wild Card 
SELECT * FROM Worker WHERE FIRST_NAME LIKE '%N_';
SELECT * FROM Worker ORDER BY SALARY DESC;
-- DISTINCT KEYWORD 
SELECT  DISTINCT LAST_NAME FROM Worker;
-- GROUP BY without aggregation is DISTINCT 
SELECT LAST_NAME, COUNT(LAST_NAME) FROM Worker GROUP BY LAST_NAME;
-- AVERAGE SALARY PER DEPARTMENT 
SELECT DEPARTMENT, AVG(SALARY) FROM Worker GROUP BY DEPARTMENT;
-- MINIMUM SALARY 
SELECT DEPARTMENT, MIN(SALARY) FROM Worker GROUP BY DEPARTMENT;
-- MAXIMUM SALARY 
SELECT DEPARTMENT, MAX(SALARY) FROM Worker GROUP BY DEPARTMENT;
-- TOTAL SALARY 
SELECT DEPARTMENT, SUM(SALARY) FROM Worker GROUP BY DEPARTMENT;
-- GROUP BY HAVING 
SELECT DEPARTMENT, COUNT(DEPARTMENT) FROM Worker GROUP BY DEPARTMENT HAVING COUNT(DEPARTMENT)=1;
